import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { Providers } from "./Services/Providers";
import { Toaster } from "sonner";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Olooja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <Toaster
          position="top-right"
          richColors={false}
          closeButton
          expand={false}
          visibleToasts={3}
          toastOptions={{
            unstyled: false,
            className: 'custom-toast',
            duration: 5000,
            classNames: {
              error: 'toast-error',
              success: 'toast-success',
              warning: 'toast-warning',
              info: 'toast-info',
              loading: 'toast-loading',
            },
          }}
          theme="light"
        />
      </body>
    </html>
  );
}