import { ITransaction } from "../Types/Interfaces/ITransactions";

export const transactionConstant: ITransaction[] = [
    {
        slug: "txn-001",
        reference: "REF-OLJ-2026-78901",
        amount: "100000",
        status: "successful",
        created_at: "2026-03-12T10:00:00Z",
        payment_method: "bank_transfer",
        description: "LPG Gas Purchase - 200kg",
        meta: {
            quantity: 200,
            gas_type_id: 1,
            amount: 100000,
            delivery_address: "15 Adeola Odeku Street, VI, Lagos",
            delivery_date: "2026-03-22",
            delivery_type: "Home Delivery",
            recurring: 0,
            end_after: 1,
            payment_method: "bank_transfer",
            callback_url: "https://example.com/callback",
            date_picked: 1742382000,
            order_number: "ORD-001",
            description: "LPG Gas Purchase - 200kg"
        },
        order_details: {
            slug: "ord-001",
            order_number: "ORD-001",
            quantity: 200,
            address: "15 Adeola Odeku Street, VI, Lagos",
            delivery_date: "2026-03-22",
            delivery_type: "Home Delivery",
            status: "pending",
            gas_price: "500",
            total_amount: "100000",
            order_history: 2,
            created_at: "2026-03-12T10:00:00Z",
            payment_status: "paid",
            credit_line_used: 50000,
            order_confirmed: 1
        }
    },
    {
        slug: "txn-002",
        reference: "REF-OLJ-2026-78902",
        amount: "72000",
        status: "successful",
        created_at: "2026-03-13T11:00:00Z",
        payment_method: "card",
        description: "LPG Gas Purchase - 150kg",
        meta: {
            quantity: 150,
            gas_type_id: 1,
            amount: 72000,
            delivery_address: "23 Herbert Macaulay Way, Yaba",
            delivery_date: "2026-03-24",
            delivery_type: "Pickup",
            recurring: 0,
            end_after: 1,
            payment_method: "card",
            callback_url: "https://example.com/callback",
            date_picked: 1742468400,
            order_number: "ORD-002",
            description: "LPG Gas Purchase - 150kg"
        },
        order_details: {
            slug: "ord-002",
            order_number: "ORD-002",
            quantity: 150,
            address: "23 Herbert Macaulay Way, Yaba",
            delivery_date: "2026-03-24",
            delivery_type: "Pickup",
            status: "confirmed",
            gas_price: "480",
            total_amount: "72000",
            order_history: 3,
            created_at: "2026-03-13T11:00:00Z",
            payment_status: "paid",
            credit_line_used: 0,
            order_confirmed: 1
        }
    },
    {
        slug: "txn-003",
        reference: "REF-OLJ-2026-78903",
        amount: "147000",
        status: "successful",
        created_at: "2026-03-10T09:00:00Z",
        payment_method: "credit_line",
        description: "LPG Gas Purchase - 300kg",
        meta: {
            quantity: 300,
            gas_type_id: 1,
            amount: 147000,
            delivery_address: "45 Admiralty Road, Lekki",
            delivery_date: "2026-03-20",
            delivery_type: "Home Delivery",
            recurring: 0,
            end_after: 1,
            payment_method: "credit_line",
            callback_url: "https://example.com/callback",
            date_picked: 1742209200,
            order_number: "ORD-003",
            description: "LPG Gas Purchase - 300kg"
        },
        order_details: {
            slug: "ord-003",
            order_number: "ORD-003",
            quantity: 300,
            address: "45 Admiralty Road, Lekki",
            delivery_date: "2026-03-20",
            delivery_type: "Home Delivery",
            status: "delivered",
            gas_price: "490",
            total_amount: "147000",
            order_history: 4,
            created_at: "2026-03-10T09:00:00Z",
            payment_status: "paid",
            credit_line_used: 147000,
            order_confirmed: 1
        }
    },
    {
        slug: "txn-004",
        reference: "REF-OLJ-2026-78904",
        amount: "51000",
        status: "failed",
        created_at: "2026-03-08T15:00:00Z",
        payment_method: "card",
        description: "LPG Gas Purchase - 100kg",
        meta: {
            quantity: 100,
            gas_type_id: 1,
            amount: 51000,
            delivery_address: "Plot 5, Banana Island, Ikoyi",
            delivery_date: "2026-03-18",
            delivery_type: "Home Delivery",
            recurring: 0,
            end_after: 1,
            payment_method: "card",
            callback_url: "https://example.com/callback",
            date_picked: 1741618800,
            order_number: "ORD-004",
            description: "LPG Gas Purchase - 100kg"
        },
        order_details: {
            slug: "ord-004",
            order_number: "ORD-004",
            quantity: 100,
            address: "Plot 5, Banana Island, Ikoyi",
            delivery_date: "2026-03-18",
            delivery_type: "Home Delivery",
            status: "cancelled",
            gas_price: "510",
            total_amount: "51000",
            order_history: 2,
            created_at: "2026-03-08T15:00:00Z",
            payment_status: "unpaid",
            credit_line_used: 0,
            order_confirmed: 0
        }
    },
    {
        slug: "txn-005",
        reference: "REF-OLJ-2026-78905",
        amount: "123750",
        status: "pending",
        created_at: "2026-03-11T12:00:00Z",
        payment_method: "bank_transfer",
        description: "LPG Gas Purchase - 250kg",
        meta: {
            quantity: 250,
            gas_type_id: 1,
            amount: 123750,
            delivery_address: "17 Allen Avenue, Ikeja",
            delivery_date: "2026-03-23",
            delivery_type: "Pickup",
            recurring: 0,
            end_after: 1,
            payment_method: "bank_transfer",
            callback_url: "https://example.com/callback",
            date_picked: 1742295600,
            order_number: "ORD-005",
            description: "LPG Gas Purchase - 250kg"
        },
        order_details: {
            slug: "ord-005",
            order_number: "ORD-005",
            quantity: 250,
            address: "17 Allen Avenue, Ikeja",
            delivery_date: "2026-03-23",
            delivery_type: "Pickup",
            status: "confirmed",
            gas_price: "495",
            total_amount: "123750",
            order_history: 4,
            created_at: "2026-03-11T12:00:00Z",
            payment_status: "paid",
            credit_line_used: 0,
            order_confirmed: 1
        }
    },
    {
        slug: "txn-006",
        reference: "REF-OLJ-2026-78906",
        amount: "90900",
        status: "pending",
        created_at: "2026-03-09T14:30:00Z",
        payment_method: "card",
        description: "LPG Gas Purchase - 180kg",
        meta: {
            quantity: 180,
            gas_type_id: 1,
            amount: 90900,
            delivery_address: "12B Glover Road, Ikoyi",
            delivery_date: "2026-03-21",
            delivery_type: "Home Delivery",
            recurring: 0,
            end_after: 1,
            payment_method: "card",
            callback_url: "https://example.com/callback",
            date_picked: 1742122800,
            order_number: "ORD-006",
            description: "LPG Gas Purchase - 180kg"
        },
        order_details: {
            slug: "ord-006",
            order_number: "ORD-006",
            quantity: 180,
            address: "12B Glover Road, Ikoyi",
            delivery_date: "2026-03-21",
            delivery_type: "Home Delivery",
            status: "pending",
            gas_price: "505",
            total_amount: "90900",
            order_history: 1,
            created_at: "2026-03-09T14:30:00Z",
            payment_status: "pending",
            credit_line_used: 0,
            order_confirmed: 0
        }
    },
    {
        slug: "txn-007",
        reference: "REF-OLJ-2026-78907",
        amount: "85000",
        status: "successful",
        created_at: "2026-03-07T16:45:00Z",
        payment_method: "wallet",
        description: "CNG Gas Purchase - 170kg",
        meta: {
            quantity: 170,
            gas_type_id: 2,
            amount: 85000,
            delivery_address: "8 Kofo Abayomi Street, VI, Lagos",
            delivery_date: "2026-03-19",
            delivery_type: "Home Delivery",
            recurring: 1,
            frequency: "weekly",
            frequency_number: 1,
            start_date: "2026-03-19",
            end_date: "2026-06-19",
            end_after: 12,
            payment_method: "wallet",
            callback_url: "https://example.com/callback",
            date_picked: 1741970700,
            order_number: "ORD-007",
            description: "CNG Gas Purchase - 170kg (Recurring)"
        },
        order_details: {
            slug: "ord-007",
            order_number: "ORD-007",
            quantity: 170,
            address: "8 Kofo Abayomi Street, VI, Lagos",
            delivery_date: "2026-03-19",
            delivery_type: "Home Delivery",
            status: "recurring",
            gas_price: "500",
            total_amount: "85000",
            order_history: 5,
            created_at: "2026-03-07T16:45:00Z",
            payment_status: "paid",
            credit_line_used: 0,
            order_confirmed: 1
        }
    },
    {
        slug: "txn-008",
        reference: "REF-OLJ-2026-78908",
        amount: "120000",
        status: "successful",
        created_at: "2026-03-06T13:20:00Z",
        payment_method: "bank_transfer",
        description: "LPG Gas Purchase - 240kg",
        meta: {
            quantity: 240,
            gas_type_id: 1,
            amount: 120000,
            delivery_address: "25 Broad Street, Marina, Lagos",
            delivery_date: "2026-03-17",
            delivery_type: "Pickup",
            recurring: 0,
            end_after: 1,
            payment_method: "bank_transfer",
            callback_url: "https://example.com/callback",
            date_picked: 1741871400,
            order_number: "ORD-008",
            description: "LPG Gas Purchase - 240kg"
        },
        order_details: {
            slug: "ord-008",
            order_number: "ORD-008",
            quantity: 240,
            address: "25 Broad Street, Marina, Lagos",
            delivery_date: "2026-03-17",
            delivery_type: "Pickup",
            status: "completed",
            gas_price: "500",
            total_amount: "120000",
            order_history: 6,
            created_at: "2026-03-06T13:20:00Z",
            payment_status: "paid",
            credit_line_used: 0,
            order_confirmed: 1
        }
    }
];
